ALTER TABLE "Task"
ALTER COLUMN "estimatedHours" TYPE DOUBLE PRECISION USING "estimatedHours"::DOUBLE PRECISION,
ALTER COLUMN "actualHours" TYPE DOUBLE PRECISION USING "actualHours"::DOUBLE PRECISION;

ALTER TABLE "TaskTemplate"
ALTER COLUMN "estimatedHours" TYPE DOUBLE PRECISION USING "estimatedHours"::DOUBLE PRECISION;
