import type { PortfolioContentData } from './types';

export const DEFAULT_PORTFOLIO_CONTENT: PortfolioContentData = {
  hero: {
    verifiedBadge: '✓ Verificado',
    headlineLine1: 'Transformo Ideias em ',
    headlineLine2: 'Negócios Digitais',
    headlineLine3: 'Que Geram',
    rotatingWords: ['Lucro', 'Impacto', 'Valor', 'Leads'],
    subheadline:
      'Crio interfaces, landing pages e soluções digitais com foco em performance, conversão e experiência — do planejamento à entrega final.',
    serviceHighlights: [
      { label: 'Landing Pages', icon: 'layout-template', active: true },
      { label: 'Automações', icon: 'zap', active: true },
      { label: 'Sistemas', icon: 'code', active: true },
      { label: 'UI/UX', icon: 'sparkles', active: true },
    ],
    primaryCta: {
      label: 'Quero Criar Meu Projeto',
      hrefType: 'whatsapp',
      href: 'https://api.whatsapp.com/send/?phone=554797086965&text=Olá! Gostaria de saber mais sobre seus serviços',
    },
    secondaryCta: {
      label: 'Ver Projetos',
      hrefType: 'section',
      targetSection: 'projetos',
    },
    microcopy:
      'Resposta rápida • Planejamento personalizado • Orçamento sem compromisso',
    dashboardPreview: {
      searchLabel: 'projeto.digital/dashboard',
      statusLabel: 'Online',
      badge: 'Projeto em construção',
      title: 'Landing page de alta conversão',
      progressLabel: '78% pronto',
      progressValue: 78,
      secondaryProgressLabel: 'do briefing ao deploy',
      cards: [
        {
          label: 'Design',
          value: 'UI clara',
          icon: 'sparkles',
          tone: 'text-violet-200',
        },
        {
          label: 'Desenvolvimento',
          value: 'Next.js',
          icon: 'code',
          tone: 'text-cyan-200',
        },
        {
          label: 'Conversão',
          value: '+Leads',
          icon: 'trending-up',
          tone: 'text-emerald-200',
        },
      ],
      processLabel: 'Processo aplicado',
      processMicrocopy: 'do briefing ao deploy',
      desktopProcessSteps: [
        'Diagnóstico',
        'Estratégia',
        'Design',
        'Desenvolvimento',
        'Otimização',
        'Entrega',
      ],
      mobileProcessSteps: ['Estratégia', 'Construção', 'Entrega'],
      previewTitle: 'Preview do projeto',
      previewBadge: 'Responsivo',
      metricsTitle: 'Indicadores',
      metrics: [
        { value: '+43%', label: 'conversão média' },
        { value: '95+', label: 'performance' },
        { value: '2h', label: 'resposta' },
      ],
    },
  },
  about: {
    badge: 'Quem está por trás do código',
    titleLine1: 'Não é só código.',
    titleHighlight: 'É resultado.',
    subtitleTemplate:
      '{years}+ anos transformando ideias em soluções digitais que geram valor real.',
    availabilityLabel: 'Disponível',
    techTitle: 'Stack Tecnológica',
    technologies: [
      'Next.js',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Node.js',
      'Prisma',
      'PostgreSQL',
      'Firebase',
      'Stripe',
      'ShadCN UI',
      'Framer Motion',
      'Docker',
    ],
    satisfaction: {
      value: '98%',
      label: 'Clientes satisfeitos',
      microcopy: 'Recorrentes',
    },
    differentiator: {
      title: 'Foco em Resultados',
      description:
        'Não entrego apenas código. Entrego soluções que impactam seu negócio.',
      items: [
        { icon: 'shield', label: 'Código Seguro', active: true },
        { icon: 'zap', label: 'Performance', active: true },
        { icon: 'users', label: 'Comunicação', active: true },
        { icon: 'check-circle', label: 'Qualidade', active: true },
      ],
    },
    cta: {
      title: 'Vamos conversar?',
      description: 'Me conta sobre o seu projeto. Resposta em até 2 horas.',
      primaryLabel: 'Falar no WhatsApp',
      secondaryLabel: 'Copiar email',
      copiedLabel: 'Email copiado!',
    },
  },
  services: {
    titlePrefix: 'Serviços e',
    titleHighlight: 'Investimento',
    subtitle:
      'Soluções digitais completas com preços transparentes. Escolha o serviço ideal para seu negócio ou solicite uma proposta personalizada.',
    services: [
      {
        name: 'Landing Pages de Alta Conversão',
        icon: 'trending-up',
        description:
          'Páginas otimizadas para converter visitantes em clientes. Design persuasivo, copy estratégico e performance excepcional.',
        features: [
          'Copywriting persuasivo',
          'Design otimizado para conversão',
          'A/B Testing incluso',
          'Relatório de performance',
          'SEO on-page',
          'Integração com analytics',
        ],
        price: 'A partir de R$ 997',
        delivery: '5-7 dias',
        popular: true,
        badge: 'Mais Vendido',
        cta: 'Quero Uma Landing Page',
        results: '+43% conversão média',
        guarantee: 'Satisfação garantida ou refaço de graça',
        active: true,
        position: 0,
        bgColor: 'bg-emerald-100',
        borderColor: 'border-emerald-300',
        iconBg: 'bg-emerald-200',
        iconColor: 'text-emerald-700',
        badgeBg: 'bg-emerald-500',
        priceColor: 'text-emerald-700',
        tagColor: 'bg-emerald-50 text-emerald-700',
        featureDot: 'text-emerald-500',
      },
      {
        name: 'Sistemas Web Completos',
        icon: 'code',
        description:
          'Sistemas personalizados para automatizar processos, gerenciar dados e escalar seu negócio com tecnologia de ponta.',
        features: [
          'Painel administrativo',
          'Banco de dados otimizado',
          'API RESTful documentada',
          'Autenticação e autorização',
          'Relatórios customizados',
          'Suporte técnico 30 dias',
        ],
        price: 'A partir de R$ 2.997',
        delivery: '15-30 dias',
        popular: false,
        badge: 'Sob Medida',
        cta: 'Quero Um Sistema',
        results: '98% uptime garantido',
        guarantee: '1 mês de suporte grátis',
        active: true,
        position: 1,
        bgColor: 'bg-blue-100',
        borderColor: 'border-blue-300',
        iconBg: 'bg-blue-200',
        iconColor: 'text-blue-700',
        badgeBg: 'bg-blue-500',
        priceColor: 'text-blue-700',
        tagColor: 'bg-blue-50 text-blue-700',
        featureDot: 'text-blue-500',
      },
      {
        name: 'E-commerce Profissional',
        icon: 'shopping-cart',
        description:
          'Lojas virtuais completas com integração de pagamentos, gestão de estoque e dashboard de vendas em tempo real.',
        features: [
          'Pagamentos via Stripe/PIX',
          'Painel de produtos e estoque',
          'Relatórios de vendas',
          'Carrinho abandonado',
          'Área do cliente',
          'Treinamento incluso',
        ],
        price: 'A partir de R$ 3.997',
        delivery: '20-35 dias',
        popular: false,
        badge: 'Completo',
        cta: 'Quero Minha Loja Virtual',
        results: 'Suporte a 10k+ produtos',
        guarantee: 'Configuração completa inclusa',
        active: true,
        position: 2,
        bgColor: 'bg-purple-100',
        borderColor: 'border-purple-300',
        iconBg: 'bg-purple-200',
        iconColor: 'text-purple-700',
        badgeBg: 'bg-purple-500',
        priceColor: 'text-purple-700',
        tagColor: 'bg-purple-50 text-purple-700',
        featureDot: 'text-purple-500',
      },
      {
        name: 'UI/UX Design Profissional',
        icon: 'palette',
        description:
          'Interfaces modernas e intuitivas que encantam usuários e aumentam o tempo de permanência no seu site.',
        features: [
          'Prototipagem interativa',
          'Design System completo',
          'Testes de usabilidade',
          'UI responsiva (mobile-first)',
          'Paleta de cores estratégica',
          'Ícones e ilustrações',
        ],
        price: 'A partir de R$ 1.497',
        delivery: '7-14 dias',
        popular: false,
        badge: 'Premium',
        cta: 'Quero Um Design Incrível',
        results: 'Nota 95+ no Lighthouse',
        guarantee: 'Revisões ilimitadas',
        active: true,
        position: 3,
        bgColor: 'bg-pink-100',
        borderColor: 'border-pink-300',
        iconBg: 'bg-pink-200',
        iconColor: 'text-pink-700',
        badgeBg: 'bg-pink-500',
        priceColor: 'text-pink-700',
        tagColor: 'bg-pink-50 text-pink-700',
        featureDot: 'text-pink-500',
      },
      {
        name: 'Otimização de Performance',
        icon: 'zap',
        description:
          'Melhore drasticamente a velocidade e performance do seu site atual para aumentar conversões e ranqueamento SEO.',
        features: [
          'Análise completa de performance',
          'Otimização de código e assets',
          'Melhoria de SEO técnico',
          'Configuração de CDN',
          'Cache inteligente',
          'Relatório antes/depois',
        ],
        price: 'A partir de R$ 797',
        delivery: '3-7 dias',
        popular: false,
        badge: 'Rápido',
        cta: 'Acelerar Meu Site',
        results: 'Até 3x mais rápido',
        guarantee: 'Resultado comprovado ou dinheiro de volta',
        active: true,
        position: 4,
        bgColor: 'bg-amber-100',
        borderColor: 'border-amber-300',
        iconBg: 'bg-amber-200',
        iconColor: 'text-amber-700',
        badgeBg: 'bg-amber-500',
        priceColor: 'text-amber-700',
        tagColor: 'bg-amber-50 text-amber-700',
        featureDot: 'text-amber-500',
      },
      {
        name: 'Consultoria Técnica',
        icon: 'bar-chart-3',
        description:
          'Análise completa da sua presença digital com recomendações estratégicas para otimizar resultados e reduzir custos.',
        features: [
          'Auditoria técnica completa',
          'Plano de ação estratégico',
          'Mentoria personalizada',
          'Relatório executivo detalhado',
          'Análise de concorrência',
          'Roadmap de implementação',
        ],
        price: 'A partir de R$ 497',
        delivery: '3-5 dias',
        popular: false,
        badge: 'Estratégico',
        cta: 'Agendar Consultoria',
        results: 'Diagnóstico em 48h',
        guarantee: 'Relatório detalhado garantido',
        active: true,
        position: 5,
        bgColor: 'bg-teal-100',
        borderColor: 'border-teal-300',
        iconBg: 'bg-teal-200',
        iconColor: 'text-teal-700',
        badgeBg: 'bg-teal-500',
        priceColor: 'text-teal-700',
        tagColor: 'bg-teal-50 text-teal-700',
        featureDot: 'text-teal-500',
      },
    ],
    finalCta: {
      title: 'Não Encontrou o Que Precisava?',
      description:
        'Cada negócio é único. Me conte sobre seu projeto e receba uma proposta personalizada em até 2 horas, sem compromisso.',
      label: 'Solicitar Proposta Personalizada',
      microcopy:
        'Resposta em até 2 horas • Sem compromisso • Satisfação garantida',
    },
  },
  process: {
    badge: 'Como funciona',
    titlePrefix: 'Da ideia ao',
    titleHighlight: 'lançamento',
    titleSuffix: 'em 4 passos',
    subtitle: 'Processo transparente, sem surpresas, sem dor de cabeça.',
    includedLabel: 'O que está incluído:',
    steps: [
      {
        step: '01',
        title: 'Discovery',
        description:
          'Entendemos seu negócio, objetivos e definimos a estratégia.',
        details: [
          'Briefing e objetivos',
          'Análise de mercado',
          'Estratégia definida',
        ],
        duration: '1-2 dias',
        image:
          'https://images.unsplash.com/photo-1552664730-d307ca884978?q=75&w=1200&auto=format&fit=crop',
        color: 'from-blue-500 to-cyan-500',
        active: true,
        position: 0,
      },
      {
        step: '02',
        title: 'Planejamento',
        description: 'Roadmap claro com tecnologias, cronograma e milestones.',
        details: [
          'Arquitetura definida',
          'Stack tecnológico',
          'Cronograma visual',
        ],
        duration: '2-3 dias',
        image:
          'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=75&w=1200&auto=format&fit=crop',
        color: 'from-purple-500 to-pink-500',
        active: true,
        position: 1,
      },
      {
        step: '03',
        title: 'Desenvolvimento',
        description: 'Código limpo, atualizações diárias e feedback constante.',
        details: [
          'Sprints ágeis',
          'Atualizações no WhatsApp',
          'Revisões por etapa',
        ],
        duration: '7-30 dias',
        image:
          'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=75&w=1200&auto=format&fit=crop',
        color: 'from-blue-600 to-cyan-600',
        active: true,
        position: 2,
      },
      {
        step: '04',
        title: 'Lançamento',
        description: 'Publicação, testes de performance e suporte pós-entrega.',
        details: [
          'Deploy otimizado',
          'Testes Lighthouse',
          'Testes de Carga',
          'Suporte 30 dias',
        ],
        duration: '1-2 dias',
        image:
          'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=75&w=1200&auto=format&fit=crop',
        color: 'from-green-500 to-emerald-500',
        active: true,
        position: 3,
      },
    ],
    guarantees: [
      { icon: 'shield', label: 'Satisfação Garantida', active: true },
      { icon: 'zap', label: 'Performance Premium', active: true },
      { icon: 'message-circle', label: 'Comunicação Direta', active: true },
      { icon: 'clock', label: 'Prazo Garantido', active: true },
    ],
    finalCta: {
      title: 'Vamos começar?',
      description:
        'Me conta sua ideia. Em até 2 horas você recebe um plano claro.',
      label: 'Falar no WhatsApp',
    },
  },
  contact: {
    titlePrefix: 'Vamos construir algo',
    titleHighlight: 'NOVO',
    subtitlePrefix: 'Me chama no WhatsApp. Em menos de',
    subtitleHighlight: '2 horas',
    subtitleSuffix: 'você já tem um plano claro para o seu projeto.',
    primaryCtaLabel: 'Falar no WhatsApp',
    separatorLabel: 'ou também',
    emailLabel: 'Email',
    copiedEmailLabel: 'Copiado!',
    phoneLabel: 'Ligar',
    trustMicrocopy:
      'Resposta em até 2h • Sem compromisso • Satisfação garantida',
  },
  projects: {
    organizerTabs: [
      'Projetos',
      'Case Studies',
      'Landing Pages',
      'Apps',
      'Automações',
    ],
  },
  settings: {
    publicPageButtonLabel: 'Ver página',
    defaultWhatsappMessage: 'Olá! Gostaria de conversar sobre um projeto',
  },
};
